// export const lightconeData = [
//   { name: "Time Waits for No One", path: "Abundance", imgUrl: "assets/lightcones/Time Waits for No One.webp", rarity: "gold" },
//   { name: "Sleep Like the Dead", path: "The Hunt", imgUrl: "assets/lightcones/Sleep Like the Dead.webp", rarity: "gold" },
//   { name: "Before Dawn", path: "Erudition", imgUrl: "assets/lightcones/Before Dawn.webp", rarity: "gold" },
//   { name: "Echoes of the Coffin", path: "Abundance", imgUrl: "assets/lightcones/Echoes of the Coffin.webp", rarity: "gold" },
//   { name: "Incessant Rain", path: "Nihility", imgUrl: "assets/lightcones/Incessant Rain.webp", rarity: "gold" },
//   { name: "Moment of Victory", path: "Preservation", imgUrl: "assets/lightcones/Moment of Victory.webp", rarity: "gold" },
//   { name: "In the Name of the World", path: "Nihility", imgUrl: "assets/lightcones/In the Name of the World.webp", rarity: "gold" },
//   { name: "But the Battle Isn't Over", path: "Harmony", imgUrl: "assets/lightcones/But the Battle Isn't Over.webp", rarity: "gold" },
//   { name: "Something Irreplaceable", path: "Destruction", imgUrl: "assets/lightcones/Something Irreplaceable.webp", rarity: "gold" },
//   { name: "In the Night", path: "The Hunt", imgUrl: "assets/lightcones/In the Night.webp", rarity: "gold" },
//   { name: "Night on the Milky Way", path: "Erudition", imgUrl: "assets/lightcones/Night on the Milky Way.webp", rarity: "gold" },
//   { name: "Texture of Memories", path: "Preservation", imgUrl: "assets/lightcones/Texture of Memories.webp", rarity: "gold" },
//   { name: "Cruising in the Stellar Sea", path: "The Hunt", imgUrl: "assets/lightcones/Cruising in the Stellar Sea.webp", rarity: "gold" },
//   { name: "On the Fall of an Aeon", path: "Destruction", imgUrl: "assets/lightcones/On the Fall of an Aeon.webp", rarity: "gold" },
//   { name: "Before the Tutorial Mission Starts", path: "Nihility", imgUrl: "assets/lightcones/Before the Tutorial Mission Starts.webp", rarity: "purple" },
//   { name: "Today Is Another Peaceful Day", path: "Erudition", imgUrl: "assets/lightcones/Today Is Another Peaceful Day.webp", rarity: "purple" },
//   { name: "Nowhere to Run", path: "Destruction", imgUrl: "assets/lightcones/Nowhere to Run.webp", rarity: "purple" },
//   { name: "Carve the Moon, Weave the Clouds", path: "Harmony", imgUrl: "assets/lightcones/Carve the Moon, Weave the Clouds.webp", rarity: "purple" },
//   { name: "Return to Darkness", path: "The Hunt", imgUrl: "assets/lightcones/Return to Darkness.webp", rarity: "purple" },
//   { name: "This Is Me!", path: "Preservation", imgUrl: "assets/lightcones/This Is Me!.webp", rarity: "purple" },
//   { name: "We Will Meet Again", path: "Nihility", imgUrl: "assets/lightcones/We Will Meet Again.webp", rarity: "purple" },
//   { name: "Warmth Shortens Cold Nights", path: "Abundance", imgUrl: "assets/lightcones/Warmth Shortens Cold Nights.webp", rarity: "purple" },
//   { name: "The Seriousness of Breakfast", path: "Erudition", imgUrl: "assets/lightcones/The Seriousness of Breakfast.webp", rarity: "purple" },
//   { name: "Woof! Walk Time!", path: "Destruction", imgUrl: "assets/lightcones/Woof! Walk Time!.webp", rarity: "purple" },
//   { name: "Past and Future", path: "Harmony", imgUrl: "assets/lightcones/Past and Future.webp", rarity: "purple" },
//   { name: "River Flows in Spring", path: "The Hunt", imgUrl: "assets/lightcones/River Flows in Spring.webp", rarity: "purple" },
//   { name: "We Are Wildfire", path: "Preservation", imgUrl: "assets/lightcones/We Are Wildfire.webp", rarity: "purple" },
//   { name: "Fermata", path: "Nihility", imgUrl: "assets/lightcones/Fermata.webp", rarity: "purple" },
//   { name: "Quid Pro Quo", path: "Abundance", imgUrl: "assets/lightcones/Quid Pro Quo.webp", rarity: "purple" },
//   { name: "Geniuses' Repose", path: "Erudition", imgUrl: "assets/lightcones/Geniuses' Repose.webp", rarity: "purple" },
//   { name: "Under the Blue Sky", path: "Destruction", imgUrl: "assets/lightcones/Under the Blue Sky.webp", rarity: "purple" },
//   { name: "Dance! Dance! Dance!", path: "Harmony", imgUrl: "assets/lightcones/Dance! Dance! Dance!.webp", rarity: "purple" },
//   { name: "Subscribe for More!", path: "The Hunt", imgUrl: "assets/lightcones/Subscribe for More!.webp", rarity: "purple" },
//   { name: "Trend of the Universal Market", path: "Preservation", imgUrl: "assets/lightcones/Trend of the Universal Market.webp", rarity: "purple" },
//   { name: "Resolution Shines As Pearls of Sweat", path: "Nihility", imgUrl: "assets/lightcones/Resolution Shines As Pearls of Sweat.webp", rarity: "purple" },
//   { name: "Perfect Timing", path: "Abundance", imgUrl: "assets/lightcones/Perfect Timing.webp", rarity: "purple" },
//   { name: "Make the World Clamor", path: "Erudition", imgUrl: "assets/lightcones/Make the World Clamor.webp", rarity: "purple" },
//   { name: "A Secret Vow", path: "Destruction", imgUrl: "assets/lightcones/A Secret Vow.webp", rarity: "purple" },
//   { name: "Planetary Rendezvous", path: "Harmony", imgUrl: "assets/lightcones/Planetary Rendezvous.webp", rarity: "purple" },
//   { name: "Swordplay", path: "The Hunt", imgUrl: "assets/lightcones/Swordplay.webp", rarity: "purple" },
//   { name: "Landau's Choice", path: "Preservation", imgUrl: "assets/lightcones/Landau's Choice.webp", rarity: "purple" },
//   { name: "Eyes of the Prey", path: "Nihility", imgUrl: "assets/lightcones/Eyes of the Prey.webp", rarity: "purple" },
//   { name: "Shared Feeling", path: "Abundance", imgUrl: "assets/lightcones/Shared Feeling.webp", rarity: "purple" },
//   { name: "The Birth of the Self", path: "Erudition", imgUrl: "assets/lightcones/The Birth of the Self.webp", rarity: "purple" },
//   { name: "The Moles Welcome You", path: "Destruction", imgUrl: "assets/lightcones/The Moles Welcome You.webp", rarity: "purple" },
//   { name: "Memories of the Past", path: "Harmony", imgUrl: "assets/lightcones/Memories of the Past.webp", rarity: "purple" },
//   { name: "Only Silence Remains", path: "The Hunt", imgUrl: "assets/lightcones/Only Silence Remains.webp", rarity: "purple" },
//   { name: "Day One of My New Life", path: "Preservation", imgUrl: "assets/lightcones/Day One of My New Life.webp", rarity: "purple" },
//   { name: "Good Night and Sleep Well", path: "Nihility", imgUrl: "assets/lightcones/Good Night and Sleep Well.webp", rarity: "purple" },
//   { name: "Post-Op Conversation", path: "Abundance", imgUrl: "assets/lightcones/Post-Op Conversation.webp", rarity: "purple" },
//   { name: "Sagacity", path: "Erudition", imgUrl: "assets/lightcones/Sagacity.webp", rarity: "blue" },
//   { name: "Mediation", path: "Harmony", imgUrl: "assets/lightcones/Mediation.webp", rarity: "blue" },
//   { name: "Hidden Shadow", path: "Nihility", imgUrl: "assets/lightcones/Hidden Shadow.webp", rarity: "blue" },
//   { name: "Pioneering", path: "Preservation", imgUrl: "assets/lightcones/Pioneering.webp", rarity: "blue" },
//   { name: "Mutual Demise", path: "Destruction", imgUrl: "assets/lightcones/Mutual Demise.webp", rarity: "blue" },
//   { name: "Multiplication", path: "Abundance", imgUrl: "assets/lightcones/Multiplication.webp", rarity: "blue" },
//   { name: "Adversarial", path: "The Hunt", imgUrl: "assets/lightcones/Adversarial.webp", rarity: "blue" },
//   { name: "Passkey", path: "Erudition", imgUrl: "assets/lightcones/Passkey.webp", rarity: "blue" },
//   { name: "Meshing Cogs", path: "Harmony", imgUrl: "assets/lightcones/Meshing Cogs.webp", rarity: "blue" },
//   { name: "Loop", path: "Nihility", imgUrl: "assets/lightcones/Loop.webp", rarity: "blue" },
//   { name: "Defense", path: "Preservation", imgUrl: "assets/lightcones/Defense.webp", rarity: "blue" },
//   { name: "Shattered Home", path: "Destruction", imgUrl: "assets/lightcones/Shattered Home.webp", rarity: "blue" },
//   { name: "Fine Fruit", path: "Abundance", imgUrl: "assets/lightcones/Fine Fruit.webp", rarity: "blue" },
//   { name: "Darting Arrow", path: "The Hunt", imgUrl: "assets/lightcones/Darting Arrow.webp", rarity: "blue" },
//   { name: "Data Bank", path: "Erudition", imgUrl: "assets/lightcones/Data Bank.webp", rarity: "blue" },
//   { name: "Chorus", path: "Harmony", imgUrl: "assets/lightcones/Chorus.webp", rarity: "blue" },
//   { name: "Void", path: "Nihility", imgUrl: "assets/lightcones/Void.webp", rarity: "blue" },
//   { name: "Amber", path: "Preservation", imgUrl: "assets/lightcones/Amber.webp", rarity: "blue" },
//   { name: "Collapsing Sky", path: "Destruction", imgUrl: "assets/lightcones/Collapsing Sky.webp", rarity: "blue" },
//   { name: "Cornucopia", path: "Abundance", imgUrl: "assets/lightcones/Cornucopia.webp", rarity: "blue" },
//   { name: "Arrows", path: "The Hunt", imgUrl: "assets/lightcones/Arrows.webp", rarity: "blue" },
// ];
